version: '3.9'

services:
  api:
    image: product-api:1.0.0
    container_name: product-api
    ports:
        - 8080:8080
    restart: on-failure
    depends_on:
        - db
    environment:
        - PORT=8080
        - DATABASE_URI=postgres://productapi:password@api-db:5432/productapi
    networks:
        - api-network
  db:
    image: postgres:13-alpine
    container_name: api-db
    ports: 
      - 5433:5432
    volumes:
      - api-db-data:/var/lib/postgresql/data
      - ./sql/postgresql/000001_init_schema.up.sql:/docker-entrypoint-initdb.d/000001_init_schema.up.sql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=productapi
      - POSTGRES_DB=productapi
    networks:
      - api-network
volumes:
  api-db-data:
    external: false
networks:
  api-network:
    driver: bridge
    name: api-network